apiVersion: batch/v1
kind: Job
metadata:
  name: ckan-restore-db
spec:
  template:
    metadata:
      name: ckan-restore-db
    spec:
      nodeSelector:
        # loads data dump from hostPath
        # TODO: change to use network shared filesystem
        kubernetes.io/hostname: gke-data4dappl-default-pool-29af7936-hdzs
      containers:
      - name: ckan-restore-db
        # this image was updated with psql which is needed to restore db
        image: gcr.io/hasadna-odata/data4dappl-ckan:34085ec7df43172d33c7fb53858374af76886be1
        command:
        - "bash"
        - "-c"
        - >
          gunzip -c /var/ckan-dump/db.gz > /db &&
          ../../bin/paster --plugin=ckan db clean -c /etc/ckan/default/development.ini &&
          ../../bin/paster --plugin=ckan db load /db -c /etc/ckan/default/development.ini
        resources:
          requests:
            cpu: 5m
        volumeMounts:
        - name: etc-ckan-default
          mountPath: /etc/ckan/default
          readOnly: true
        - name: ckan-dump
          mountPath: /var/ckan-dump
      volumes:
      - name: etc-ckan-default
        secret:
          secretName: etc-ckan-default
      - name: ckan-dump
        hostPath: {path: /var/ckan-dump}
      restartPolicy: Never
